### ISSUE TITLE
Breaking change: strict types declaration breaks inheritance

### ISSUE THREAD

**Issue by Eseperio** [irazasyed/telegram-bot-sdk#1080]
The latest release, 3.13.0, has introduced typed variables. This causes all previously designed commands, as well as any other class that extends from this library, to stop functioning and throw a PHP Compile Error.

This change should correspond to a major version rather than a minor one.

```
Type of app\components\telegram\WhoCommand::$name must be string (as in class Telegram\Bot\Commands\Command)
```

**Comment by irazasyed** [comment]
Unfortunately we had to take this call to release it as minor version as v4 is already a major refactor moved to its own repo while we had to fix and maintain v3 too due to high usage with certain major updates due to dependency packages (like for example the guzzle security issue that caused us to update and with it, certain major upgrades were required including min. PHP requirements and so on).
