### ISSUE TITLE
[Idea] Create an updates manager class

### ISSUE THREAD

**Issue by irazasyed** [irazasyed/telegram-bot-sdk#124]
Create manager class to handle inbound updates and to automatically initialize the right class based on the inbound update type.

Idea discussed on [PHP Chat](https://phpchat.co)

**Comment by jonnywilliamson** [comment]
The idea came from looking at this:

![image](https://cloud.githubusercontent.com/assets/2513663/13651057/81e727b4-e63d-11e5-81a7-5a1593d1df09.png)


It's likely the type of update objects we have to deal with as time goes on will continually increase. We have 3 possible types as of now.

Rather than only having a `commandsHandler()` that deals with the Message Object as shown above, we s/could have a manager class that can deal with all different types of inbound Update objects.
