### ISSUE TITLE
sendVideo Actually accepts caption field

### ISSUE THREAD

**Issue by jonnywilliamson** [irazasyed/telegram-bot-sdk#13]
Hi,

The [official docs](https://core.telegram.org/bots/api#available-methods) show that you can send a caption with [`sendMessage`](https://core.telegram.org/bots/api#sendmessage).

There is no mention of being able to send a caption with [`sendVideo`](https://core.telegram.org/bots/api#sendvideo), however when you actually send a video in a normal client (ie iOS app, desktop etc) you CAN set a caption.

I have added the caption variable to the [`sendVideo`](https://core.telegram.org/bots/api#sendvideo) method in your library and surprise surprise it works perfectly.....but it seems like it was missed when they wrote the documents on the official Telegram site.

Would you accept a PR with this added or do you prefer to keep you library in strict adherence to the official docs?

**Comment by irazasyed** [comment]
Hi @jonnywilliamson,

That's a great find man :+1:

I'm open for the PR. Since the library itself is unofficial and as already stated by their support, they're still in process of improving things. Maybe they missed it and would be made available in their next update or so.

Just make sure you properly test several times though. If it's something that temporarily works sometimes and doesn't work always, then it's not really a good idea to add it.

I'll drop a message to their support and query about it as well. Still waiting for the response for the #9 issue.

Thanks!

**Comment by jonnywilliamson** [comment]
Sorry was out of country with work.

Will do this v shortly.

**Comment by irazasyed** [comment]
No problem. Take your time! Thanks.

**Comment by jonnywilliamson** [comment]
Thought I was going mad.

A couple of days ago I checked the docs and no mention of caption on the sendVideo Method. Looked at it today and there it was!

Quick check of internet archive shows I wasn't going mad:

Before
![before](https://cloud.githubusercontent.com/assets/2513663/8888250/a4978bfe-329d-11e5-8665-66e034744c65.png)


And now:
![after](https://cloud.githubusercontent.com/assets/2513663/8888252/a9ae19fa-329d-11e5-94d3-f336c2556dae.png)

**Comment by irazasyed** [comment]
Ah i see. They must've added recently. So it's official now, good :+1: 

Thanks for the contribution @jonnywilliamson. Appreciate it :)

**Comment by jonnywilliamson** [comment]
Actually before this gets closed I'm having a lot of trouble with the sendVideo method (at least on iOS - hence my delay in sending the PR).

Here are 3 video files that are on my phone (each less than 400Kb) please download them to a folder.

[Video1](https://www.dropbox.com/s/kc7q2992ti1pe3t/1.mov?dl=0)
[Video2](https://www.dropbox.com/s/buw7kuhe6bsbw3t/2.mp4?dl=0)
[Video3](https://www.dropbox.com/s/i6nrg65wo4kb9nw/3.mp4?dl=0)

Now, here's a simple route I created to send them to my Telegram account:
```php
Route::get('/test', function(){
    Telegram::sendVideo('<myId>', '/tmp/1.mov');
    Telegram::sendVideo('<myId>', '/tmp/2.mp4');
    Telegram::sendVideo('<myId>', '/tmp/3.mp4');
});
```

This is how they all appeared when they arrived on my phone:
![1](https://cloud.githubusercontent.com/assets/2513663/8889068/56200c16-32c1-11e5-850f-48b871599a80.png)


This is how they looked when I downloaded them - notice no thumbnails:
![2](https://cloud.githubusercontent.com/assets/2513663/8889072/710196ee-32c1-11e5-9862-d63622cd4020.png)

However, if I leave the conversation and return to it they magically appear:
![3](https://cloud.githubusercontent.com/assets/2513663/8889073/81acdc38-32c1-11e5-9e16-1f40277a2383.png)

However NONE of the videos will play. If I try I get this screen:
![4](https://cloud.githubusercontent.com/assets/2513663/8889074/8d949e1e-32c1-11e5-8f45-158ab34ba821.png)

If I send the videos as a DOCUMENT using this library, everything works perfectly.

If I send the videos via the Telegram app on my phone to another user they all work too.

Any thoughts?

**Comment by irazasyed** [comment]
So i just tested this a few times and it seems like some sort of bug on their end, not the library.

Because, I saved the video to the camera roll on iOS and it saved the video just fine and i was able to play it from the Photos app too. However, It didn't play within the Telegram app itself (like you reported).

I also tested this on the Telegram Mac client, The video loads fine including the thumbnail, etc. So it could be bug with Telegram iOS app..not sure how its handling the videos within bots API. (I didn't test with Android though). Maybe you should report this to their support and provide this issue link, Let them take a look as well.

I'll probably do that as well but they don't seem to be responding at all (Still waiting for those 2 other issues, not even opened/seen my messages).

**Comment by irazasyed** [comment]
Response from support:

> There is currently a bug in the iOS version, which looks horribly similar to this issue.

> Soo.. That might just be it, but.. haven't gotten confirmation from the dev side of the bots yet, which means i'm 50/50 on that ;) as soon as I get a definitive answer on that (or one of my volunteer coworkers) we'll let you know :)

**Comment by jonnywilliamson** [comment]
Its good they got back to you. I had sent a couple of tweets to the @telegram account and pointed to these issues too.

Appreciate the feedback!

**Comment by siyanew** [comment]
Recently Telegram add width and height and duration in its document but videos send with bacl image preview , I found some videos that sent correctly, I think its about encoding of files.
Did you find anything @jonnywilliamson ?

**Comment by dvadvaa** [comment]
The problem still exists!

**Comment by foremtehan** [comment]
This issue still exists! I'm sure this is not related to their end! becuase when i use `file_get_content` it send video with correct thumbnail,
