### ISSUE TITLE
Get user response (command) from keyboard without slash

### ISSUE THREAD

**Issue by frencisdrame** [irazasyed/telegram-bot-sdk#137]
Hi
I want get a command from custom keyboard, without slash.
I read in other issue and inthe documentation, that this is not possible, the commands must always start with the ‘/’ symbol.
But in many bots i see that is possible.
For example @TriviaBot
I thought to get the string before the trigger start and add "/" to the string but without success.
Other solutions?

**Comment by irazasyed** [comment]
Hey @frencisdrame 
Like you already know, It isn't possible in this SDK but I do have plans to create a trigger method to trigger any command from anywhere.

That is however not my priority at the moment as I need to get the V3 out ASAP.

But what you can however do is, You can manually execute the command by reading the text and either executing it from the same command or just respond with whatever it has to do. Since after the system passes through the commands handler, you still get the full update object which can be used for anything.

**Comment by irazasyed** [comment]
Closed in last commit. Will be released in V3.
