### ISSUE TITLE
Asynchronous Requests - PHP Script execution time optimization

### ISSUE THREAD

**Issue by suiluj** [irazasyed/telegram-bot-sdk#197]
Hello,
I have problems with my bot when there are many user requests at the same time.
So i found the telegram-bot-sdk (which I did not use before) and try to use async requests to get faster performance.

I created a short test script to test the exection time which is working well:
```
$time_start = microtime(true);
		for ($i=1;$i<=100;$i++){
			$response = $this->telegram->sendMessage([
					'chat_id' => Hereiam::gettelegram("juliuschatid"),
					'text' => $i . '. Nachricht'
			]);
		}
		$time_end = microtime(true);
		$time = $time_end - $time_start;
		echo "$time seconds";
```

I change the async true/false value in the seconde parameter as described [in the docs](https://telegram-bot-sdk.readme.io/docs/asynchronous-requests).

Output for async requests: `0.056188106536865 seconds`
Output for sync requests: `16.119078874588 seconds`

So the async requests are great.
But there is one thing that bothers me:
When i open my test url which starts the script. The URL is still loading until every message is sent.
I expected the website to be complete loaded after this very short time.
What am I doing wrong?

Thanks for your help
Regards
Julius

**Comment by jonnywilliamson** [comment]
I would check your config again that the test URL is definiately starting the script shown above with async enabled and not a different bit of code that has async disabled.

However, 2 things to note.

1) If you use async, you can NEVER tell if your message was sent correctly (server doesn't wait for a reply from telegram to say that they got it properly for processing). So that's a big issue if you actually want to know if your message will be sent!

and 
2) https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

More than 1 message / sec = spamming and therefore your messages will return an error....but you've set async to true so you'll never know that is happening....

**Comment by suiluj** [comment]
Okay thanks.

I use a background process now. So my webhook script is ready for the next request immediately.

**Comment by jonnywilliamson** [comment]
Much better option.
