### ISSUE TITLE
How to switch bot tokens in a loop in Laravel?

### ISSUE THREAD

**Issue by zvermafia** [irazasyed/telegram-bot-sdk#230]
I need to make many request to Telegram API in short time, but to avoid hitting limit I would like to use multiple bot tokens.

For example:
```
foreach ($items as $item)
{
    Telegram::setBotToken('bot_token');

    $response = Telegram::getChatMembersCount(['chat_id' => $item->chat_id]);
    // ...
}
```

**Comment by zvermafia** [comment]
I found getter and setter methods for token:
```
Telegram::getAccessToken('bot_token');
Telegram::setAccessToken('bot_token');
```

Those are what I needed. The problem is solved.

**Comment by irazasyed** [comment]
You could also set all your bot tokens in config (If you're using `3.*@dev` version) and then just do:

```php
Telegram::bot('bot_name')->getMe();
```

Put that in a loop with the list of bot names and it'll take care of using correct bot token and other details. It supports multi-bot.

**Comment by jonnywilliamson** [comment]
@zvermafia Can I ask out of interest how many message your are sending?

I ask because the docs state:
![image](https://cloud.githubusercontent.com/assets/2513663/18045470/d808167a-6dca-11e6-8c08-5ec22a20950f.png)


So giving yourself a buffer of only sending say 25/sec:

That's `25 * 60 * 60 * 24 = 2,160,000` messages a day. (vs 2.6 million if you use 30/sec).

I'm fascinated to know what sort of app needs 2.1 million messages sent every day!! (Please note I'm not saying you're spamming because you can't really with Telegram bots, but I'd love to know more about what needs this volume of messages!)

Thanks.

**Comment by zvermafia** [comment]
@jonnywilliamson I must update channels' data (participants count, title, ...) hourly (now ~400 channels). If I use only one bot for these goals, then after ~230 channels (getChat(), getChatMembersCount()) I get error #429. If even I use sleep(2) after each channel iteration...
