### ISSUE TITLE
TelegramSDKException in GuzzleHttpClient.php line 114:

### ISSUE THREAD

**Issue by jobs2008** [irazasyed/telegram-bot-sdk#397]
im beginer in laravel 

i have problem in run this code 

`
use Telegram\Bot\Laravel\Facades\Telegram;

Route::get('/', function () {
    $updates = Telegram::getUpdates();
    dd($updates);
});
`

error code : 
`
TelegramSDKException in GuzzleHttpClient.php line 114:
cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
`
please help me step by step

**Comment by jonnywilliamson** [comment]
Did you create your own SSL cert to test this with?

Did you follow these instructions? 

https://core.telegram.org/bots/api#setwebhook
https://core.telegram.org/bots/self-signed

**Comment by omankopyor** [comment]
i have same problem like that. maybe this can solve your problem
go to "\vendor\irazasyed\telegram-bot-sdk\src\HttpClients" and open "GuzzleHttpClient.php"
edit 
$this->client = $client ?: new Client(); 
in my file line 49 to 
$this->client = $client ?: new Client(['verify' => false ]);
this can solve my guzzle error because access https telegram.

**Comment by NabiKAZ** [comment]
You don't should any change files of core framework.

Fore resolve this problem:
- First download this file: https://curl.se/ca/cacert.pem
- And then put this in `php.ini` file:
```curl.cainfo=PATH\cacert.pem```
- The `PATH` in here is absolute location of `cacert.pem` file.
- And then restart web service.
