### ISSUE TITLE
error when calling a command

### ISSUE THREAD

**Issue by hadikmsh** [irazasyed/telegram-bot-sdk#465]
Hi.
when i call a command i got this error:
Argument 3 passed to Telegram\Bot\Commands\Command::make() must be of the type array, none given
i use "irazasyed/telegram-bot-sdk": "dev-develop", and your sample laravel project to start with that.

can you help me?
thanks.

**Comment by jonnywilliamson** [comment]
Yes there's a bug in the code due to a lot of changes recently. Its in the command make method signature.

I see the problem and will try and fix as soon as possible.

Annoyingly due another small bug in the test suite, this managed to jump over that part of the code instead of catching it. So that's annoying 😠 , but both will be fixed soon.

**Comment by jonnywilliamson** [comment]
If https://github.com/irazasyed/telegram-bot-sdk/pull/467 gets merged this should be fixed.
