### ISSUE TITLE
use non-default bot cause error.

### ISSUE THREAD

**Issue by hadikmsh** [irazasyed/telegram-bot-sdk#479]
hi
 i use Telegram::bot('second') to call second bot, but it cause an error.
Type error: Argument 3 passed to Telegram\Bot\Commands\CommandBus::execute() must be of the type array, none given.

can you help me?

**Comment by jonnywilliamson** [comment]
Are you using the latest develop branch code? I think you must be to be getting this info.

If so, then you'll see that we detect commands in an update object when it has an "entity" field with the type of bot_command.

This allows us to detect exactly what command was sent to the bot, where precisely it is in the message text etc. It allows us to deal with multiple commands in a message.

These entity details must be passed to the command parsing code for the command to be detected, parsed and executed.

At the moment it seems (due to the recent change) you are not passing these entity details to the command execute code.

For an example of what that looks like here's a json representation.

```json
{
    "update_id": 888888888,
    "message": {
        "message_id": 307,
        "from": {
            "id": 12443287,
            "is_bot": false,
            "first_name": "Jonathan",
            "last_name": "Williamson",
            "language_code": "en-GB"
        },
        "chat": {
            "id": 99999999,
            "first_name": "Jonathan",
            "last_name": "Williamson",
            "type": "private"
        },
        "date": 1507293503,
		"text": "/wx eidw einn egcc /wx kbos kbdl",
        "entities": [
            {
                "offset": 0,
                "length": 3,
                "type": "bot_command"
            },
            {
                "offset": 19,
                "length": 3,
                "type": "bot_command"
            }
        ]
    }
}
```
