### ISSUE TITLE
Suddenly webhook stopped working

### ISSUE THREAD

**Issue by khalilst** [irazasyed/telegram-bot-sdk#51]
Hello
I applyed webhook in my telegram bot and it was working fine. SSL provided by claudeflare.
But suddenly some hours later, it stopped.
Everything was OK. But now just Long Polling is working and not Webhook.
Do you have any idea?
Thanks in advance

**Comment by irazasyed** [comment]
Hi,

No idea what could be the issue. You should probably check to see if CloudFlare settings are correct, check the URL is accessible, check logs, etc.

**Comment by khalilst** [comment]
Hello again dear
I moved my bot to a vps. Setup a Self-Signed Certificate to my domain and then setup Webhook.
Everything worked fine. But a few days later, it stopped again. Remove and Set Webhook couple of times and setWebhook returns True, but bot gets nothing from Telegram API. Is there a way to see error message to find out what's wrong?
I don't like this part of telegram, its really bad engineered! And its support is really sick.

**Comment by jonnywilliamson** [comment]
I don't like this part of telegram, its really bad engineered! And its support is really sick.


Really? Do you expect us all to help when you are so rude?

**Comment by irazasyed** [comment]
@khalilst If telegram never sends you a POST request, How would you even debug that?

Check for a few things like:
- The Bot Token is Valid.
- The Link is Accessible.
- The Self-signed certificate is valid and not tampered and or missing its private key, etc.
- Test the webhook with something like Postman or other tools to simulate the request.
- Keep in mind, When you use CloudFlare's SSL feature, you're not supposed to submit a self-signed certificate. In order to use your certificate, you need to first upload it to your CloudFlare account (This would be a paid feature BTW) and only then it would work. There's a chance where, Telegram is trying to verify the certificate you uploaded against the certificate of CF and since it fails, it isn't making any requests. So please check that. What you can also do is, Don't route requests to your webhook through CloudFlare.
- You could use something like letsencrypt.org to get a valid certificate (It's valid only for 90 days! You need to renew every 90 days but that can be automated).
- If all the above fail, try with https://ngrok.com/ (Setup a sub-domain), they'll give you a valid HTTPS sub-domain which can then be used to map to your Homestead (If you use or your local machine) and it would also have a panel which you can use to monitor all the requests that are being made to that URL. So using this URL, once you set the webhook. You can then send some message from Telegram and monitor the dashboard to see if any incoming requests are being made and check all its headers, body/payload, etc. and the response from your script (So if there's some error or output, you can read it right there itself). Obviously, this is for testing only and not something you should be doing for your production server.

If it's still not working, then i guess you should talk to the support and discuss your problem with them as i doubt we could do anything from our end, since it's not under our control nor it has got anything to do with the SDK itself. Hope that helps!

**Comment by khalilst** [comment]
@irazasyed Thank you for your complete guide. I don't want to insult to you
and your team because of your great work. And it is obvious your SDK is a
Top Layer on Telegram APIs and the problem was in there [core]. BTW I
apologize for making @jonnywilliamson feel uncomfortable.

Dear Syed, everything was and is fine in our side. There is some issues in
Telegram. After some days, it started to work again. I talked to T-Support.
This is summary of my message:

I need a method to validate self-signed certificate in order to solve
problems. There was no clear error message, except returning TRUE by
telegram.

And this is support answer:

After talking to the developers, there were some issues that should be
solved now, so I hope it's indeed working again for you. We've already
asked for extra methods so that webhooks can indeed be checked decently, I
hope it will be implemented in the near future.

It is a fact that Telegram Core (and not you) has a weak framework for Bots
and I think this will cause any attempt in this field ends to failure. Some
time after simple webhook reset (remove and set it again) causes to work
again and some times not. But every time I lost some clients.
Best Regards

**Comment by irazasyed** [comment]
@khalilst You're most welcome :)

I'm glad it's working for you now and thanks for posting the answer from the support. Indeed the core is not really solid and we know the fact that, they sadly do not follow any standards and or best practises. However, since they're quite new, lets give them some time and hopefully the API will get more mature with time and we'll get a much more proper API to communicate with.

As for @jonnywilliamson, Not sure what's up with him. Maybe just some misunderstanding i think.

P.S Just to clear, We're not a team nor i have anyone from my team working on this project. Everyone involved in this project are simply contributors helping us improve the SDK for everyone using this project (That's the best part of open-source projects!) and i really appreciate all the contributions from all our contributors. Whether that's by sending a PR or opening an issue ticket to report a bug/suggestions/request for a new feature or anything else. Everyone is welcome to do that and will be appreciated as always.

**Comment by jonnywilliamson** [comment]
@khalilst Ok I apologise, I first read your post and I thought you were criticising @irazasyed's SDK, which didn't seem fair. 

But seeing it again I think it was actually Telegram you were complaining about, so sorry about that. Hopefully Telegram will add some more methods soon to improve debugging etc.
