### ISSUE TITLE
pending_update_count

### ISSUE THREAD

**Issue by karrarjasim** [irazasyed/telegram-bot-sdk#583]
how can i clear pending updates ?
the resopnse of: `https://api.telegram.org/bot<token>/getWebhookInfo`
give me pending_update_count:1560 !!!

**Comment by yongkylie** [comment]
I don't know best practice of this issue, but usually I just do delete the webhook and set it again to my endpoint

1. https://api.telegram.org/bot<token>/deleteWebhook.
2. https://api.telegram.org/bot<token>/setWebhook?url=https://example.com/api/<token> (as mentioned in https://core.telegram.org/bots/api#setwebhook).

Just make sure your code don't have any errors, because Telegram server will keep trying to send the exact message to your webhook URL and make the pending count keep increasing.

**Comment by zhenyang0405** [comment]
You can clear pending_update_count by setting drop_pending_updates=True to clear pending_update_count.

1. https://api.telegram.org/bot/setWebhook?url='https://example.com"&drop_pending_updates=True
2. https://api.telegram.org/bot/deleteWebhook?drop_pending_updates=True

These two methods will be able to clear the pending_update_count.
