### ISSUE TITLE
how can share all contact  in telegram bot 

### ISSUE THREAD

**Issue by Kasra-S** [irazasyed/telegram-bot-sdk#589]
Hi 
i want sahre name and numberphone my contact whith telegram key 
how can?

**Comment by yongkylie** [comment]
Can you please explain more about telegram key you mentioned?

By sharing all name and number phone in your contact do you mean that you want to move all of your contact from `Device A` to `Device B` using Telegram?

The answer is yes, and no.

Yes you can, if your bot already have all of your contacts data from your device.

No you can't,  if your bot don't have your contacts data yet. As I know, Telegram app can't extract you contacts data (Correct me if I'm wrong).
Because there's no documentation in telegram official API (read here https://core.telegram.org/bots/api#sendcontact) that have such method to extract contacts data from device. And also, this library is build based on that documentation.
