### ISSUE TITLE
Manually executing commands

### ISSUE THREAD

**Issue by raffiismail** [irazasyed/telegram-bot-sdk#59]
Currently doing this:
$api = new Api(TELEGRAM_API_KEY);
// let's assume CustomCommand has been implemented and works through Telegram App
$api->addCommand(MINE\Bot\Commands\CustomCommand::class);
$updates = $api->getWebhookUpdates();

// command is passed without prefixed '/'
$api->getCommandBus()->execute('customcommand', 'string of arguments', $updates);

CustomCommand works on its own via telegram app with the exact 'string of arguments'
but when called manually in the above manner, it does not respond in the same manner given the same arguments

Also tried the following:
$api->getCommandBus()->handler('/customcommand string of arguments', $updates);
Without any success

There is some confusion between API->getWebhookUpdates() which returns Update object
and API->getUpdates() which returns array of Update objects
but this is minor.

What could I be doing wrong?

**Comment by irazasyed** [comment]
I just tested this here and everything works as expected. Checklist:

1. Check if class exists and the namespace/path is valid as well as the filename is correct.
2. Do `composer dump-autoload` once.
3. Check the command name set in command class is same as the one you passed in execute method.
4. Check to see if you have any exceptions in command class and or something that's terminating the script due to an exception or a condition that's not met.
5. See what's the output of `$api->getCommands();` to confirm the command was registered properly and shows your command class in list.

**Comment by raffiismail** [comment]
I've manually inserted my code in your vendor source.
It works. So it has to be a bug on my implementation.
Thanks man!

**Comment by irazasyed** [comment]
I see. That's bad. Should not modify vendor files.

You're welcome. I'm closing this ticket then. If any other issues, please open a new one. Thanks!
