### ISSUE TITLE
Please modify support laravel 6.0

### ISSUE THREAD

**Issue by eric2100** [irazasyed/telegram-bot-sdk#660]
Please modify support laravel 6.0.
thank you.

**Comment by matthewnessworthy** [comment]
There's an open PR for this https://github.com/irazasyed/telegram-bot-sdk/pull/661

**Comment by iBotPeaches** [comment]
It looks like this is already in develop - https://github.com/irazasyed/telegram-bot-sdk/commit/8a2c5fa699d39c9019ced5036a3cb956c47de7d7, unforunately there are a lot of breaking changes for v3.0.

If possible, a tag in the v2.0 series - since L6 doesn't seem to introduce any breaking changes would be helpful :) - I'm not ready to jump to v3 of this plugin yet - it looks quite different.

**Comment by matthewnessworthy** [comment]
@iBotPeaches perhaps https://github.com/irazasyed/telegram-bot-sdk/pull/662

**Comment by eric2100** [comment]
> @iBotPeaches perhaps #662


I also want this version.

**Comment by eric2100** [comment]
> 看起來這已經在開發[--8a2c5fa](https://github.com/irazasyed/telegram-bot-sdk/commit/8a2c5fa699d39c9019ced5036a3cb956c47de7d7)，不幸的是v3.0有很多重大變化。
> 
> 如果可能的話，v2.0系列中的標籤 - 因為L6似乎沒有引入任何重大改變會有所幫助:) - 我還沒準備好跳轉到這個插件的v3 - 它看起來很不一樣。

3.0 Support for new APIs,But it has lost a lot of features, and it seems that it has not been maintained for a long time.

**Comment by irazasyed** [comment]
It has been merged into master which doesn't have any breaking changes. I'll tag it for now since many still use 2.0. But it is recommended to migrate to 3.0.

**Comment by eric2100** [comment]
> It has been merged into master which doesn't have any breaking changes. I'll tag it for now since many still use 2.0. But it is recommended to migrate to 3.0.

tag:master it use 3.0 version? So can't be used in laravel 6.0.
What I need is the 2.0 version, thank you.
