### ISSUE TITLE
"[Error]: Photo has unsupported extension", for remote files.

### ISSUE THREAD

**Issue by ping** [irazasyed/telegram-bot-sdk#68]
Was testing the support for remote files added in 67e17a5 and got an error ``[Error]: Photo has unsupported extension.``

```php
$tg = new Api($telegram_token);
$img_url = 'https://www.instagram.com/p/-kfo63BQes/media/?size=l';
$response = $tg->sendPhoto(
	array('chat_id' => $chat_id
		, 'photo' => $img_url
		, 'caption' => $my_caption)
);
```

This can be worked around by artificially adding a fake param ``x=.jpg`` making it
``$img_url = 'https://www.instagram.com/p/-kfo63BQes/media/?size=l&x=.jpg';`` 

In my opinion, there shouldn't be file extension checks for remote files because an image/video url can be in any format.

**Comment by irazasyed** [comment]
That check is from Telegram Bot API servers and has got nothing to do with this SDK. That's something we can't really control. If they say it's not supported, then its not and you need to provide the one which is supported.

Besides that, The SDK won't do auto redirect. So instead of providing that link, you could rather provide a direct link to the image like this (Same URL which you provided above):
```https://igcdn-photos-e-a.akamaihd.net/hphotos-ak-xft1/t51.2885-15/e35/12301416_855648747889404_1852916307_n.jpg```

This should work fine.

**Comment by ping** [comment]
@irazasyed Thanks for the clarification.

However, the redirect works fine in my testing with ``https://www.instagram.com/p/-kfo63BQes/media/?size=l&x=.jpg``. There was no need to provide the direct image link.

**Comment by irazasyed** [comment]
No problem and if you say it does redirect, then that's good then. :+1: 

I didn't test that fully. It's still WIP.
