### ISSUE TITLE
No documentation for setWebhook

### ISSUE THREAD

**Issue by jearsonbgomez** [irazasyed/telegram-bot-sdk#856]
Upon reading the documentation at https://telegram-bot-sdk.readme.io/reference#setwebhook it says that "This endpoint's documentation is currently experiencing difficulties and will be back online shortly.". How do I implement the setWebhook on laravel?

**Comment by wudug** [comment]
$response=Telegram::setWebhook(['url' => 'yoururl/{someuniqueid}/webhook']);
  return Response()->json($response);

it's recommended that you use your telegram bot token in the place of someuniqueid
your return should be true if the webhook is set correctly

you should also set the above URL in your routes file so that you can get updates from it

**Comment by wudug** [comment]
> 
> 
> Upon reading the documentation at https://telegram-bot-sdk.readme.io/reference#setwebhook it says that "This endpoint's documentation is currently experiencing difficulties and will be back online shortly.". How do I implement the setWebhook on laravel?

$response=Telegram::setWebhook(['url' => 'yoururl/{someuniqueid}/webhook']);
return Response()->json($response);

it's recommended that you use your telegram bot token in the place of someuniqueid
your return should be true if the webhook is set correctly

you should also set the above URL in your routes file so that you can get updates from it

**Comment by jearsonbgomez** [comment]
Thank you!
