### ISSUE TITLE
write extensions for this library

### ISSUE THREAD

**Issue by amir1376** [irazasyed/telegram-bot-sdk#894]
I like this library and working on some features to add 
but I faced with some problems here...

My solution is to have a `MainHandler` that handles incoming updates
this handler contains some nested handlers according to user wish(like `PageNavigationHandler` that I already developed this one ,.... )
Main Handler iterates over handlers that was added to it ,if any of them can handle this update then take it and handle ,then whole update handling procedure will be done successfully

in your library there is a `CommandHandler` that does not return any result that I can figure out if that was handled update  or not, because of that ,this can't cooperate with custom handlers so I have to write another CommandHandler to cooperate with other similar handlers too..
so here we have two Command Handlers first one that belongs to main Api and another is one that developed and actually used !

its good idea to have a pure Api (don't have any handlers like Commands embed inside) that can be extended and customized more with extra features from other packages

**Comment by irazasyed** [comment]
Hey @amir1376,

Thanks for showing interest in contributing to this project.

We've actually moved to a new organization where we've made significant changes to make the library more extendible.

Because it's a major change, we're looking forward to release it as V4. However, we lack documentation for this version and while some contributors have tried to add the docs, they too have been busy due to which it couldn't be finished and hence, we haven't released it yet.

That said, you're more than welcome to explore the latest version and contribute/suggest changes.

Please explore the packages/project here: https://github.com/telegram-bot-sdk

And the library itself: https://github.com/telegram-bot-sdk/telegram-bot-sdk

I'll close this issue ticket but you may open a new one in the above link.

Thanks!

**Comment by amir1376** [comment]
cool thanks, going to see v4 
I hope I can help

**Comment by amir1376** [comment]
@irazasyed 
cool thanks , going to see v4
I hope I can help on that
