### ISSUE TITLE
"Message not supported" when replying with document

### ISSUE THREAD

**Issue by reauv** [irazasyed/telegram-bot-sdk#96]
I'm trying to build an bot that will use the giphy API for getting a random gif for the supplied keyword, but I can't get the gifs to work in Telegram. I know it's possible because other bots are doing it. 
When I use the `replyWithPhoto` it end up showing a static photo of the gif, after some searching I read that you should send gifs as document, but when I use `replyWithDocument` I get a message in telegram that says
```
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.
```
Ofcourse I am using the latest version of Telegram.

I have a feeling that it's caused by a wrong MIME type but I have no idea how to change that.
This is the code I am using for the command:

```
<?php

namespace App\Commands;

use Telegram\Bot\Actions;
use Telegram\Bot\Commands\Command;

class GiphyCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = "giphy";

    /**
     * @var string Command Description
     */
    protected $description = "Post a random GIF";

    /**
     * @inheritdoc
     */
    public function handle($arguments)
    {
        $this->replyWithDocument(['document' => 'http://media2.giphy.com/media/FiGiRei2ICzzG/giphy.gif']);
    }
}
```

Any idea what is causing this?

**Comment by irazasyed** [comment]
As per the error, it seems like you're using Telegram Web version?

Have you checked in your mobile device? Or try to check in an actual desktop client?

Also @jonnywilliamson should be able to help you as well, he was having trouble with the gifs showing up static the other day. Lets wait for him to give his input. In the mean time, please test with an actual device or desktop client instead of web version.

**Comment by reauv** [comment]
On the iOS application I get a similar error
```
This message is not supported on your version of Telegram. Update the app to view: http://telegram.org/update
```
and on the OS X application I get a `Media Unsupported` error.

**Comment by ihoru** [comment]
I've tested on my own the same file.
When I'm trying to upload that file to Telegram with this code:
```php

            $rs = Telegram::sendDocument(
                [
                    'chat_id'  => $chat->chat_id,
                    'document' => 'http://media2.giphy.com/media/FiGiRei2ICzzG/giphy.gif',
                ]
            );
```
I get this response:
```php
    "document" => Telegram\Bot\Objects\Document {#652
      #items: array:5 [
        "file_name" => "giphy.gif.mp4"
        "mime_type" => "video/mp4"
        "thumb" => Telegram\Bot\Objects\PhotoSize {#647
          #items: array:4 [
            "file_id" => "AAQCABMyulkqAATyg4Otr9R-s7c-AAIC"
            "file_size" => 934
            "width" => 90
            "height" => 32
          ]
        }
        "file_id" => "BQADAgADBwADPpS5Ca0lKxBlpRuoAg"
        "file_size" => 23349
      ]
    }
```

As you can see it decided that mime_type is video/mp4.
But when I sent this file to the bot from client it had such data:
```php
  "document" => array:5 [
    "file_name" => "giphy.gif"
    "mime_type" => "image/gif"
    "thumb" => array:5 [
      "file_id" => "AAQCABOxIoMqAAS1UYrWduU1pDIHAAIC"
      "file_size" => 1286
      "file_path" => "thumb/file_0.jpg"
      "width" => 90
      "height" => 31
    ]
    "file_id" => "BQADAgADLQAD17N5AAE3boO9dT7RjAI"
    "file_size" => 426811
  ]
```
Correct mime-type.

I've checked downloaded file on my local machine:
$ file giphy.gif 
giphy.gif: GIF image data, version 89a, 500 x 176

I've tested SDK versions: 1.0 and 2.0 - the same result.
I know exactly, that it worked before (I've sent gifs from bot while testing something).

I've tested the same from command line:
$ curl https://api.telegram.org/bot***/sendDocument -F 'chat_id=7975895' -F 'document=@/home/ihoru/desktop/giphy.gif'
{"ok":true,"result":{"message_id":27373,"from":{***},"chat":{"id":7975895,"first_name":"\u0418\u0433\u043e\u0440\u044c","last_name":"\u041f\u043e\u043b\u044f\u043a\u043e\u0432","username":"ihoru","type":"private"},"date":1451880416,"document":{"file_name":"giphy.gif.mp4","mime_type":"video\/mp4","thumb":{"file_id":"AAQCABMyulkqAATyg4Otr9R-s7c-AAIC","file_size":934,"width":90,"height":32},"file_id":"BQADAgADBQADN_ybB3ks4P1TTWYmAg","file_size":23349}}}
As you can see mime_type: video/mp4

Thats why, I am sure the problem is on the Telegram's side.
They have deployed some changes on 1 January. I think, they could make a bug in new code.

I suggest to write to special Telegram user: @BotSupport with description of the problem.

**Comment by ihoru** [comment]
Oh, I've understood =)
Telegram Dev team created new client update, but could not release it because of Apple approve waiting.
And new client will work with that type of file, but old clients will be broken. Fuck Yeah! :'(

**Comment by reauv** [comment]
Alright, thanks for checking! So I guess Telegram are converting the gifs to mp4 for performance reasons. Strange thing is there is actually mp4 support, but you get an actual video player. Let's hope they add support for playing mp4 inline like a gif in the next updates. I'll close this for now and keep an eye on the Telegram updates.

**Comment by lososerg** [comment]
Yep, seems like converting gifs to mpeg4 videos make their download speed up to 20x faster due to up to 95% less disk space 'consumption'. https://telegram.org/blog/gif-revolution

**Comment by jonnywilliamson** [comment]
@irazasyed and @all 

Yeah, not much more I can add to this, started around Jan 1st/2nd and since then I've had exactly the same issues sending animated gifs etc.

Basically two things have happened. They've changed the way their code works (as shown above) and have obviously updated their apps:
![image](https://cloud.githubusercontent.com/assets/2513663/12087507/84b27b6a-b2cb-11e5-836c-b60028e44ab8.png)


However, it seems that the APP store takes a break over the Christmas period and doesn't approve updates etc:
![image](https://cloud.githubusercontent.com/assets/2513663/12087518/9c465dc8-b2cb-11e5-9ded-2ec525e1d101.png)


However I don't know why the android/windows/desktop versions haven't been released....

My bet is that within approx 48hours Apple will have approved the new ios app and the others will appear too and this issue will resolve itself.

Of course they may also change the way `sendPhoto` works to allow animated gifs so we don't  have to use `sendDocument` anymore...

This looks interesting:
https://core.telegram.org/bots/api#inlinequeryresultgif

**Comment by irazasyed** [comment]
@ihoru @jonnywilliamson Thanks guys for sharing all the information.

Technically speaking, They were supposed to notify devs about this change and at least giving some time for people to upgrade. Besides that, they shouldn't have updated their codes even before their client updates to their end users are pushed out :|

**Comment by ihoru** [comment]
> However I don't know why the android/windows/desktop versions haven't been released....
I think they want to release everywhere at the same time...

> Of course they may also change the way sendPhoto works to allow animated gifs so we don't have to use sendDocument anymore...
sendPhoto just grubs the first screen of GIF for now...

> This looks interesting: https://core.telegram.org/bots/api#inlinequeryresultgif
BTW, they didn't give ability to send `file_id` of already uploaded photo/document it's a pity.

@irazasyed, yep, it's weird.

**Comment by reauv** [comment]
It's working correctly now with the latest update on iOS. Thanks guys!

**Comment by irazasyed** [comment]
Cool, Glad it's working for you :)

P.S Just updated iOS version and tested the new inline query bots, great stuff.
